In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

# Municipios

In [ ]:
# !wget --no-check-certificate https://download.inep.gov.br/avaliacao_da_alfabetizacao/resultados_e_metas_municipios.xlsx
# !curl -k -O https://download.inep.gov.br/avaliacao_da_alfabetizacao/resultados_e_metas_municipios.xlsx
# import requests

# url = "https://download.inep.gov.br/avaliacao_da_alfabetizacao/resultados_e_metas_municipios.xlsx"
# response = requests.get(url, verify=False)

# with open("resultados_e_metas_municipios.xlsx", "wb") as f:
#     f.write(response.content)

In [ ]:
# %ls

sample_data/

In [ ]:
df = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_municipios.xlsx",
    sheet_name="Divulgação Alfabet Municipio",
)

In [ ]:
df.columns

Index(['ANO DA AVALIAÇÃO', 'CÓDIGO UF', 'SIGLA UF', 'CÓDIGO MUNICÍPIO',
       'NOME DO MUNICÍPIO', 'REDE', 'PERCENTUAL DE ALUNOS ALFABETIZADOS (1)',
       'META 2024 (2)', 'META 2025', 'META 2026', 'META 2027', 'META 2028',
       'META 2029', 'META 2030', 'NIVEL ALFABETIZAÇÃO',
       'PERCENTUAL DE PARTICIPAÇÃO'],
      dtype='object')

In [ ]:
[
    "ANO DA AVALIAÇÃO",
    # "CÓDIGO UF",
    "SIGLA UF",
    "CÓDIGO MUNICÍPIO",
    # "NOME DO MUNICÍPIO",
    "REDE",
    "PERCENTUAL DE ALUNOS ALFABETIZADOS (1)",
    "META 2024 (2)",
    "META 2025",
    "META 2026",
    "META 2027",
    "META 2028",
    "META 2029",
    "META 2030",
    # "NIVEL ALFABETIZAÇÃO",
    "PERCENTUAL DE PARTICIPAÇÃO",
]

['ANO DA AVALIAÇÃO',
 'SIGLA UF',
 'CÓDIGO MUNICÍPIO',
 'REDE',
 'PERCENTUAL DE ALUNOS ALFABETIZADOS (1)',
 'META 2024 (2)',
 'META 2025',
 'META 2026',
 'META 2027',
 'META 2028',
 'META 2029',
 'META 2030',
 'PERCENTUAL DE PARTICIPAÇÃO']

In [ ]:
renames = {
    "ANO DA AVALIAÇÃO": "ano",
    "SIGLA UF": "sigla_uf",
    "CÓDIGO MUNICÍPIO": "id_municipio",
    "REDE": "rede",
    "PERCENTUAL DE ALUNOS ALFABETIZADOS (1)": "taxa_alfabetizacao",
    "META 2024 (2)": "meta_alfabetizacao_2024",
    "META 2025": "meta_alfabetizacao_2025",
    "META 2026": "meta_alfabetizacao_2026",
    "META 2027": "meta_alfabetizacao_2027",
    "META 2028": "meta_alfabetizacao_2028",
    "META 2029": "meta_alfabetizacao_2029",
    "META 2030": "meta_alfabetizacao_2030",
    # "NIVEL ALFABETIZAÇÃO": "nivel_alfabetizacao",
    "PERCENTUAL DE PARTICIPAÇÃO": "percentual_participacao",
}

In [ ]:
df = df[list(renames.keys())].rename(columns=renames)

In [ ]:
df = (
    df.loc[df["id_municipio"].notna()].drop(df.index[0]).reset_index(drop=True)
)

In [ ]:
df

,ano,sigla_uf,id_municipio,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2023,RO,1100015,MUNICIPAL,64.55,67.078601,69.512028,71.841093,74.058634,76.159493,78.140434,80,89.37
1,2023,RO,1100023,MUNICIPAL,62.3,65.216878,68.023909,70.706161,73.251889,75.652567,77.902777,80,89.79
2,2023,RO,1100031,MUNICIPAL,69.1,70.845029,72.530686,74.154438,75.714346,77.209042,78.6377,80,90.48
3,2023,RO,1100049,MUNICIPAL,62.51,65.390716,68.162817,70.81199,73.326986,75.699642,77.924781,80,84.44
4,2023,RO,1100056,MUNICIPAL,58.53,62.090401,65.525172,68.805091,71.906748,74.812904,77.512445,80,92.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5463,2023,GO,5221908,MUNICIPAL,97.74,80,80,80,80,80,80,80,78.18
5464,2023,GO,5222005,MUNICIPAL,89.04,80,80,80,80,80,80,80,84.88
5465,2023,GO,5222054,MUNICIPAL,78.24,78.49812,78.754009,79.007667,79.259095,79.508292,79.75526,80,94.2
5466,2023,GO,5222203,MUNICIPAL,83.76,80,80,80,80,80,80,80,92.11
5467,2023,GO,5222302,MUNICIPAL,74.44,75.292945,76.126555,76.940653,77.735109,78.509839,79.264803,80,90.54

In [ ]:
df["ano"].unique()

array([2023], dtype=object)

In [ ]:
df["rede"].unique()

array(['MUNICIPAL'], dtype=object)

In [ ]:
# df["nivel_alfabetizacao"].unique()

In [ ]:
df["percentual_participacao"].unique()

array([89.37, 89.79, 90.48, ..., 78.38, 89.85, 84.88], dtype=object)

In [ ]:
df["percentual_participacao"].value_counts(dropna=False)

percentual_participacao
100      209
-        111
90        48
92.31     45
88.89     39
        ...
88.92      1
81.12      1
80.67      1
86.58      1
98.73      1
Name: count, Length: 1755, dtype: int64

In [ ]:
colunas_meta = [
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
    "taxa_alfabetizacao",
    "percentual_participacao",
]
for c in colunas_meta:
    df[c] = (
        df[c]
        .astype(str)  # garante que tudo seja string para aplicar strip
        .str.strip()  # remove espaços
        .replace("-", np.nan)  # substitui "-"
        .replace("> 80", "80")
        .replace(">80", "80")  # padroniza "> 80"
        .replace(",", ".", regex=True)  # se os números forem com vírgula
    )
    df[c] = df[c].astype(float)

In [ ]:
# df["nivel_alfabetizacao"] = df["nivel_alfabetizacao"].replace("-", np.nan)

In [ ]:
# df["percentual_participacao"] = df["percentual_participacao"].replace("-", np.nan)

In [ ]:
# df["nivel_alfabetizacao"].unique()

In [ ]:
df["rede"] = df["rede"].str.lower()

In [ ]:
df["id_municipio"] = df["id_municipio"].astype(str)

In [ ]:
df

,ano,sigla_uf,id_municipio,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2023,RO,1100015,municipal,64.55,67.078601,69.512028,71.841093,74.058634,76.159493,78.140434,80.0,89.37
1,2023,RO,1100023,municipal,62.30,65.216878,68.023909,70.706161,73.251889,75.652567,77.902777,80.0,89.79
2,2023,RO,1100031,municipal,69.10,70.845029,72.530686,74.154438,75.714346,77.209042,78.637700,80.0,90.48
3,2023,RO,1100049,municipal,62.51,65.390716,68.162817,70.811990,73.326986,75.699642,77.924781,80.0,84.44
4,2023,RO,1100056,municipal,58.53,62.090401,65.525172,68.805091,71.906748,74.812904,77.512445,80.0,92.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5463,2023,GO,5221908,municipal,97.74,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,78.18
5464,2023,GO,5222005,municipal,89.04,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,84.88
5465,2023,GO,5222054,municipal,78.24,78.498120,78.754009,79.007667,79.259095,79.508292,79.755260,80.0,94.20
5466,2023,GO,5222203,municipal,83.76,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,92.11
5467,2023,GO,5222302,municipal,74.44,75.292945,76.126555,76.940653,77.735109,78.509839,79.264803,80.0,90.54

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/output/br_inep_avaliacao_alfabetizacao_municipio_2023.csv",
    index=False,
)

# 2024

In [ ]:
df_2023 = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_municipios.xlsx",
    sheet_name="Divulgação Alfabet Municipio",
    skiprows=1,
)

In [ ]:
df_2023

,ANO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_TP_REDE,PC_ALUNO_ALFABETIZADO,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,NIVEIS_ALFABETIZACAO_2023,PC_AVALIADOS_LP
0,2023,11.0,RO,1100015.0,Alta Floresta D'Oeste,MUNICIPAL,64.55,67.078601,69.512028,71.841093,74.058634,76.159493,78.140434,80,3,89.37
1,2023,11.0,RO,1100023.0,Ariquemes,MUNICIPAL,62.3,65.216878,68.023909,70.706161,73.251889,75.652567,77.902777,80,3,89.79
2,2023,11.0,RO,1100031.0,Cabixi,MUNICIPAL,69.1,70.845029,72.530686,74.154438,75.714346,77.209042,78.6377,80,3,90.48
3,2023,11.0,RO,1100049.0,Cacoal,MUNICIPAL,62.51,65.390716,68.162817,70.81199,73.326986,75.699642,77.924781,80,3,84.44
4,2023,11.0,RO,1100056.0,Cerejeiras,MUNICIPAL,58.53,62.090401,65.525172,68.805091,71.906748,74.812904,77.512445,80,2,92.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5466,2023,52.0,GO,5222203.0,Vila Boa,MUNICIPAL,83.76,80,80,80,80,80,80,80,5,92.11
5467,2023,52.0,GO,5222302.0,Vila Propício,MUNICIPAL,74.44,75.292945,76.126555,76.940653,77.735109,78.509839,79.264803,80,4,90.54
5468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5469,Observação 1: municípios sem resultados são os...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5470,Observação 2: as metas definidas para os munic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_2023 = df_2023.rename(
    columns={
        "CO_MUNICIPIO": "CO_MUNICIPIO",
        "PC_AVALIADOS_LP": "PC_AVALIADOS_LP_2023",
    }
)

In [ ]:
df_2024 = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_municipios_2024.xlsx",
    sheet_name="Divulgação Alfabet Municipio",
    skiprows=1,
)

In [ ]:
df_2024.columns

Index(['ANO', 'CO_UF', 'SG_UF', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'NO_TP_REDE',
       'PC_ALUNO_ALFABETIZADO_2023', 'PC_ALUNO_ALFABETIZADO_2024',
       'META_FINAL_2024', 'META_FINAL_2025', 'META_FINAL_2026',
       'META_FINAL_2027', 'META_FINAL_2028', 'META_FINAL_2029',
       'META_FINAL_2030', 'CO_NIVEL_ALFABETIZACAO', 'PC_AVALIADOS_LP'],
      dtype='object')

In [ ]:
df_2023 = df_2023[df_2023["CO_MUNICIPIO"].notna()].copy()
df_2024 = df_2024[df_2024["CO_MUNICIPIO"].notna()].copy()

In [ ]:
df_2023["CO_MUNICIPIO"] = (
    df_2023["CO_MUNICIPIO"].astype(float).astype("Int64").astype(str)
)
df_2024["CO_MUNICIPIO"] = (
    df_2024["CO_MUNICIPIO"].astype(float).astype("Int64").astype(str)
)

In [ ]:
df_2024_original = df_2024.copy()

In [ ]:
df_2024_original

,ANO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_TP_REDE,PC_ALUNO_ALFABETIZADO_2023,PC_ALUNO_ALFABETIZADO_2024,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,CO_NIVEL_ALFABETIZACAO,PC_AVALIADOS_LP
0,2024,11.0,RO,1100015,Alta Floresta D'Oeste,MUNICIPAL,64.6,67.79,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3.0,89.869281
1,2024,11.0,RO,1100023,Ariquemes,MUNICIPAL,62.3,65.62,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3.0,88.759367
2,2024,11.0,RO,1100031,Cabixi,MUNICIPAL,69.1,75.88,70.85,72.53,74.15,75.71,77.21,78.64,80.0,4.0,92.592593
3,2024,11.0,RO,1100049,Cacoal,MUNICIPAL,62.5,65.81,65.39,68.16,70.81,73.33,75.70,77.92,80.0,3.0,92.566783
4,2024,11.0,RO,1100056,Cerejeiras,MUNICIPAL,58.5,66.81,62.09,65.53,68.81,71.91,74.81,77.51,80.0,3.0,96.442688
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5347,2024,52.0,GO,5221908,Varjão,MUNICIPAL,97.7,84.78,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,100.000000
5348,2024,52.0,GO,5222005,Vianópolis,MUNICIPAL,89.0,89.50,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,95.121951
5349,2024,52.0,GO,5222054,Vicentinópolis,MUNICIPAL,78.2,84.21,78.50,78.75,79.01,79.26,79.51,79.76,80.0,5.0,100.000000
5350,2024,52.0,GO,5222203,Vila Boa,MUNICIPAL,83.8,78.69,80.00,80.00,80.00,80.00,80.00,80.00,80.0,4.0,100.000000
5351,2024,52.0,GO,5222302,Vila Propício,MUNICIPAL,74.4,79.46,75.29,76.13,76.94,77.74,78.51,79.26,80.0,4.0,89.041096

In [ ]:
participacao_2023 = df_2023[
    ["CO_MUNICIPIO", "PC_AVALIADOS_LP_2023", "NIVEIS_ALFABETIZACAO_2023"]
]

In [ ]:
df_2024 = df_2024.merge(
    participacao_2023,
    on="CO_MUNICIPIO",
    how="left",  # usa left join para manter todos os dados de 2024
)

In [ ]:
linhas_perdidas = df_2024_original[~df_2024_original.index.isin(df_2024.index)]

# OU: comparar as chaves (mais preciso!)
municipios_antes = set(df_2024_original["CO_MUNICIPIO"])
municipios_depois = set(df_2024["CO_MUNICIPIO"])

faltando = municipios_antes - municipios_depois

# Ver as linhas inteiras que sumiram (se houver)
linhas_faltantes = df_2024_original[
    df_2024_original["CO_MUNICIPIO"].isin(faltando)
]

print("Linhas perdidas no merge:")
print(linhas_faltantes)

Linhas perdidas no merge:
Empty DataFrame
Columns: [ANO, CO_UF, SG_UF, CO_MUNICIPIO, NO_MUNICIPIO, NO_TP_REDE, PC_ALUNO_ALFABETIZADO_2023, PC_ALUNO_ALFABETIZADO_2024, META_FINAL_2024, META_FINAL_2025, META_FINAL_2026, META_FINAL_2027, META_FINAL_2028, META_FINAL_2029, META_FINAL_2030, CO_NIVEL_ALFABETIZACAO, PC_AVALIADOS_LP]
Index: []

In [ ]:
df_2024

,ANO,CO_UF,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,NO_TP_REDE,PC_ALUNO_ALFABETIZADO_2023,PC_ALUNO_ALFABETIZADO_2024,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,CO_NIVEL_ALFABETIZACAO,PC_AVALIADOS_LP,PC_AVALIADOS_LP_2023,NIVEIS_ALFABETIZACAO_2023
0,2024,11.0,RO,1100015,Alta Floresta D'Oeste,MUNICIPAL,64.6,67.79,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3.0,89.869281,89.37,3
1,2024,11.0,RO,1100023,Ariquemes,MUNICIPAL,62.3,65.62,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3.0,88.759367,89.79,3
2,2024,11.0,RO,1100031,Cabixi,MUNICIPAL,69.1,75.88,70.85,72.53,74.15,75.71,77.21,78.64,80.0,4.0,92.592593,90.48,3
3,2024,11.0,RO,1100049,Cacoal,MUNICIPAL,62.5,65.81,65.39,68.16,70.81,73.33,75.70,77.92,80.0,3.0,92.566783,84.44,3
4,2024,11.0,RO,1100056,Cerejeiras,MUNICIPAL,58.5,66.81,62.09,65.53,68.81,71.91,74.81,77.51,80.0,3.0,96.442688,92.12,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5347,2024,52.0,GO,5221908,Varjão,MUNICIPAL,97.7,84.78,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,100.000000,78.18,5
5348,2024,52.0,GO,5222005,Vianópolis,MUNICIPAL,89.0,89.50,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,95.121951,84.88,5
5349,2024,52.0,GO,5222054,Vicentinópolis,MUNICIPAL,78.2,84.21,78.50,78.75,79.01,79.26,79.51,79.76,80.0,5.0,100.000000,94.2,4
5350,2024,52.0,GO,5222203,Vila Boa,MUNICIPAL,83.8,78.69,80.00,80.00,80.00,80.00,80.00,80.00,80.0,4.0,100.000000,92.11,5
5351,2024,52.0,GO,5222302,Vila Propício,MUNICIPAL,74.4,79.46,75.29,76.13,76.94,77.74,78.51,79.26,80.0,4.0,89.041096,90.54,4

In [ ]:
renames = {
    "ANO": "ano",
    "SG_UF": "sigla_uf",
    "CO_MUNICIPIO": "id_municipio",
    "NO_TP_REDE": "rede",
    "PC_ALUNO_ALFABETIZADO_2024": "taxa_alfabetizacao_2024",
    "PC_ALUNO_ALFABETIZADO_2023": "taxa_alfabetizacao_2023",
    "META_FINAL_2024": "meta_alfabetizacao_2024",
    "META_FINAL_2025": "meta_alfabetizacao_2025",
    "META_FINAL_2026": "meta_alfabetizacao_2026",
    "META_FINAL_2027": "meta_alfabetizacao_2027",
    "META_FINAL_2028": "meta_alfabetizacao_2028",
    "META_FINAL_2029": "meta_alfabetizacao_2029",
    "META_FINAL_2030": "meta_alfabetizacao_2030",
    "CO_NIVEL_ALFABETIZACAO": "nivel_alfabetizacao_2024",
    "PC_AVALIADOS_LP": "percentual_participacao_2024",
    "PC_AVALIADOS_LP_2023": "percentual_participacao_2023",
    "NIVEIS_ALFABETIZACAO_2023": "nivel_alfabetizacao_2023",
}

In [ ]:
df_2024 = df_2024[list(renames.keys())].rename(columns=renames)

In [ ]:
df_2024

,ano,sigla_uf,id_municipio,rede,taxa_alfabetizacao_2024,taxa_alfabetizacao_2023,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao_2024,percentual_participacao_2024,percentual_participacao_2023,nivel_alfabetizacao_2023
0,2024,RO,1100015,MUNICIPAL,67.79,64.6,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3.0,89.869281,89.37,3
1,2024,RO,1100023,MUNICIPAL,65.62,62.3,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3.0,88.759367,89.79,3
2,2024,RO,1100031,MUNICIPAL,75.88,69.1,70.85,72.53,74.15,75.71,77.21,78.64,80.0,4.0,92.592593,90.48,3
3,2024,RO,1100049,MUNICIPAL,65.81,62.5,65.39,68.16,70.81,73.33,75.70,77.92,80.0,3.0,92.566783,84.44,3
4,2024,RO,1100056,MUNICIPAL,66.81,58.5,62.09,65.53,68.81,71.91,74.81,77.51,80.0,3.0,96.442688,92.12,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5347,2024,GO,5221908,MUNICIPAL,84.78,97.7,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,100.000000,78.18,5
5348,2024,GO,5222005,MUNICIPAL,89.50,89.0,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,95.121951,84.88,5
5349,2024,GO,5222054,MUNICIPAL,84.21,78.2,78.50,78.75,79.01,79.26,79.51,79.76,80.0,5.0,100.000000,94.2,4
5350,2024,GO,5222203,MUNICIPAL,78.69,83.8,80.00,80.00,80.00,80.00,80.00,80.00,80.0,4.0,100.000000,92.11,5
5351,2024,GO,5222302,MUNICIPAL,79.46,74.4,75.29,76.13,76.94,77.74,78.51,79.26,80.0,4.0,89.041096,90.54,4

In [ ]:
df_2024.columns

Index(['ano', 'sigla_uf', 'id_municipio', 'rede', 'taxa_alfabetizacao_2024',
       'taxa_alfabetizacao_2023', 'meta_alfabetizacao_2024',
       'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
       'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
       'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',
       'nivel_alfabetizacao_2024', 'percentual_participacao_2024',
       'percentual_participacao_2023', 'nivel_alfabetizacao_2023'],
      dtype='object')

In [ ]:
colunas_meta = [
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
    "taxa_alfabetizacao_2023",
    "taxa_alfabetizacao_2024",
    "percentual_participacao_2023",
    "percentual_participacao_2024",
    "nivel_alfabetizacao_2023",
    "nivel_alfabetizacao_2024",
]
for c in colunas_meta:
    df_2024[c] = (
        df_2024[c]
        .astype(str)  # garante que tudo seja string para aplicar strip
        .str.strip()  # remove espaços
        .replace("-", np.nan)  # substitui "-"
        .replace("> 80", "80")
        .replace(">80", "80")  # padroniza "> 80"
        .replace(",", ".", regex=True)  # se os números forem com vírgula
    )
    df_2024[c] = df_2024[c].astype(float)

In [ ]:
df_2024

,ano,sigla_uf,id_municipio,rede,taxa_alfabetizacao_2024,taxa_alfabetizacao_2023,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao_2024,percentual_participacao_2024,percentual_participacao_2023,nivel_alfabetizacao_2023
0,2024,RO,1100015,MUNICIPAL,67.79,64.6,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3.0,89.869281,89.37,3.0
1,2024,RO,1100023,MUNICIPAL,65.62,62.3,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3.0,88.759367,89.79,3.0
2,2024,RO,1100031,MUNICIPAL,75.88,69.1,70.85,72.53,74.15,75.71,77.21,78.64,80.0,4.0,92.592593,90.48,3.0
3,2024,RO,1100049,MUNICIPAL,65.81,62.5,65.39,68.16,70.81,73.33,75.70,77.92,80.0,3.0,92.566783,84.44,3.0
4,2024,RO,1100056,MUNICIPAL,66.81,58.5,62.09,65.53,68.81,71.91,74.81,77.51,80.0,3.0,96.442688,92.12,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5347,2024,GO,5221908,MUNICIPAL,84.78,97.7,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,100.000000,78.18,5.0
5348,2024,GO,5222005,MUNICIPAL,89.50,89.0,80.00,80.00,80.00,80.00,80.00,80.00,80.0,5.0,95.121951,84.88,5.0
5349,2024,GO,5222054,MUNICIPAL,84.21,78.2,78.50,78.75,79.01,79.26,79.51,79.76,80.0,5.0,100.000000,94.20,4.0
5350,2024,GO,5222203,MUNICIPAL,78.69,83.8,80.00,80.00,80.00,80.00,80.00,80.00,80.0,4.0,100.000000,92.11,5.0
5351,2024,GO,5222302,MUNICIPAL,79.46,74.4,75.29,76.13,76.94,77.74,78.51,79.26,80.0,4.0,89.041096,90.54,4.0

In [ ]:
df_2024.columns

Index(['ano', 'sigla_uf', 'id_municipio', 'rede', 'taxa_alfabetizacao_2024',
       'taxa_alfabetizacao_2023', 'meta_alfabetizacao_2024',
       'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
       'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
       'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',
       'nivel_alfabetizacao_2024', 'percentual_participacao_2024',
       'percentual_participacao_2023', 'nivel_alfabetizacao_2023'],
      dtype='object')

In [ ]:
# Lista de colunas fixas (que não vão para long)
id_vars = [
    "sigla_uf",
    "id_municipio",
    "rede",
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
]


# Função auxiliar para "derreter" um grupo de colunas por variável
def melt_por_variavel(df, variavel):
    colunas = [f"{variavel}_2023", f"{variavel}_2024"]
    df_melted = df_2024[id_vars + colunas].melt(
        id_vars=id_vars,
        value_vars=colunas,
        var_name="variavel_ano",
        value_name=variavel,
    )
    # Extrai o ano da string da coluna e transforma em inteiro
    df_melted["ano"] = (
        df_melted["variavel_ano"].str.extract(r"(\d{4})").astype(int)
    )
    df_melted = df_melted.drop(columns="variavel_ano")
    return df_melted


# Faz o melt para cada variável que será empilhada
df_taxa = melt_por_variavel(df_2024, "taxa_alfabetizacao")
df_nivel = melt_por_variavel(df_2024, "nivel_alfabetizacao")
df_participacao = melt_por_variavel(df_2024, "percentual_participacao")

# Junta tudo pelo conjunto de chaves
df_long = df_taxa.merge(df_nivel, on=id_vars + ["ano"]).merge(
    df_participacao, on=id_vars + ["ano"]
)

In [ ]:
df_long

,sigla_uf,id_municipio,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,nivel_alfabetizacao,percentual_participacao
0,RO,1100015,MUNICIPAL,67.08,69.51,71.84,74.06,76.16,78.14,80.0,64.60,2023,3.0,89.370000
1,RO,1100023,MUNICIPAL,65.22,68.02,70.71,73.25,75.65,77.90,80.0,62.30,2023,3.0,89.790000
2,RO,1100031,MUNICIPAL,70.85,72.53,74.15,75.71,77.21,78.64,80.0,69.10,2023,3.0,90.480000
3,RO,1100049,MUNICIPAL,65.39,68.16,70.81,73.33,75.70,77.92,80.0,62.50,2023,3.0,84.440000
4,RO,1100056,MUNICIPAL,62.09,65.53,68.81,71.91,74.81,77.51,80.0,58.50,2023,2.0,92.120000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,GO,5221908,MUNICIPAL,80.00,80.00,80.00,80.00,80.00,80.00,80.0,84.78,2024,5.0,100.000000
10700,GO,5222005,MUNICIPAL,80.00,80.00,80.00,80.00,80.00,80.00,80.0,89.50,2024,5.0,95.121951
10701,GO,5222054,MUNICIPAL,78.50,78.75,79.01,79.26,79.51,79.76,80.0,84.21,2024,5.0,100.000000
10702,GO,5222203,MUNICIPAL,80.00,80.00,80.00,80.00,80.00,80.00,80.0,78.69,2024,4.0,100.000000
10703,GO,5222302,MUNICIPAL,75.29,76.13,76.94,77.74,78.51,79.26,80.0,79.46,2024,4.0,89.041096

In [ ]:
df_long["ano"].unique()

array([2023, 2024])

In [ ]:
df_long["rede"].unique()

array(['MUNICIPAL'], dtype=object)

In [ ]:
df_long["nivel_alfabetizacao"] = df_long["nivel_alfabetizacao"].astype("Int64")

In [ ]:
df_long["nivel_alfabetizacao"].unique()

<IntegerArray>
[3, 2, 5, 1, 4, 0, <NA>]
Length: 7, dtype: Int64

In [ ]:
df_long["percentual_participacao"].unique()

array([89.37      , 89.79      , 90.48      , ..., 93.3412604 ,
       98.39228296, 88.43881857])

In [ ]:
# df["nivel_alfabetizacao"] = df["nivel_alfabetizacao"].replace("-", np.nan)

In [ ]:
# df["percentual_participacao"] = df["percentual_participacao"].replace("-", np.nan)

In [ ]:
# df["nivel_alfabetizacao"].unique()

In [ ]:
df_long["rede"] = df_long["rede"].str.lower()

In [ ]:
df_long["id_municipio"] = df_long["id_municipio"].astype(str)

In [ ]:
df_long

,sigla_uf,id_municipio,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,nivel_alfabetizacao,percentual_participacao
0,RO,1100015,municipal,67.08,69.51,71.84,74.06,76.16,78.14,80.0,64.60,2023,3,89.370000
1,RO,1100023,municipal,65.22,68.02,70.71,73.25,75.65,77.90,80.0,62.30,2023,3,89.790000
2,RO,1100031,municipal,70.85,72.53,74.15,75.71,77.21,78.64,80.0,69.10,2023,3,90.480000
3,RO,1100049,municipal,65.39,68.16,70.81,73.33,75.70,77.92,80.0,62.50,2023,3,84.440000
4,RO,1100056,municipal,62.09,65.53,68.81,71.91,74.81,77.51,80.0,58.50,2023,2,92.120000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10699,GO,5221908,municipal,80.00,80.00,80.00,80.00,80.00,80.00,80.0,84.78,2024,5,100.000000
10700,GO,5222005,municipal,80.00,80.00,80.00,80.00,80.00,80.00,80.0,89.50,2024,5,95.121951
10701,GO,5222054,municipal,78.50,78.75,79.01,79.26,79.51,79.76,80.0,84.21,2024,5,100.000000
10702,GO,5222203,municipal,80.00,80.00,80.00,80.00,80.00,80.00,80.0,78.69,2024,4,100.000000
10703,GO,5222302,municipal,75.29,76.13,76.94,77.74,78.51,79.26,80.0,79.46,2024,4,89.041096

In [ ]:
# df = pd.concat([df_2023, df_2024])

In [ ]:
df_long = df_long.sort_values(by=["ano", "sigla_uf", "id_municipio"])

In [ ]:
df_long

,sigla_uf,id_municipio,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,nivel_alfabetizacao,percentual_participacao
52,AC,1200013,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
53,AC,1200054,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
54,AC,1200104,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
55,AC,1200138,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
56,AC,1200179,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5772,TO,1721208,municipal,41.22,48.38,55.61,62.61,69.12,74.95,80.0,35.44,2024,0,90.082645
5773,TO,1721257,municipal,43.00,49.91,56.81,63.47,69.64,75.18,80.0,66.67,2024,3,88.888889
5774,TO,1721307,municipal,32.22,40.40,49.16,57.96,66.29,73.72,80.0,53.85,2024,2,100.000000
5775,TO,1722081,municipal,41.91,48.97,56.08,62.95,69.32,75.04,80.0,41.89,2024,1,81.739130
5776,TO,1722107,municipal,29.18,37.57,46.78,56.21,65.22,73.25,80.0,42.82,2024,1,88.148148

In [ ]:
df_long[df_long["ano"] == 2023]

,sigla_uf,id_municipio,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,nivel_alfabetizacao,percentual_participacao
52,AC,1200013,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
53,AC,1200054,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
54,AC,1200104,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
55,AC,1200138,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
56,AC,1200179,municipal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,<NA>,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,TO,1721208,municipal,41.22,48.38,55.61,62.61,69.12,74.95,80.0,34.4,2023,0,94.84
421,TO,1721257,municipal,43.00,49.91,56.81,63.47,69.64,75.18,80.0,36.4,2023,0,100.00
422,TO,1721307,municipal,32.22,40.40,49.16,57.96,66.29,73.72,80.0,25.0,2023,0,94.12
423,TO,1722081,municipal,41.91,48.97,56.08,62.95,69.32,75.04,80.0,35.2,2023,0,86.18
424,TO,1722107,municipal,29.18,37.57,46.78,56.21,65.22,73.25,80.0,22.0,2023,0,83.58

In [ ]:
df_long.to_csv(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/output/br_inep_avaliacao_alfabetizacao_municipio.csv",
    index=False,
)

# Brasil e UFs

In [ ]:
# !wget --no-check-certificate https://download.inep.gov.br/avaliacao_da_alfabetizacao/resultados_e_metas_ufs.xlsx

--2024-06-03 17:39:26--  https://download.inep.gov.br/avaliacao_da_alfabetizacao/resultados_e_metas_ufs.xlsx
Resolving download.inep.gov.br (download.inep.gov.br)... 200.130.24.15
Connecting to download.inep.gov.br (download.inep.gov.br)|200.130.24.15|:443... connected.
WARNING: cannot verify download.inep.gov.br's certificate, issued by ‘CN=RNP ICPEdu OV SSL CA 2019,O=Rede Nacional de Ensino e Pesquisa - RNP,C=BR’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 16139 (16K) [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet]
Saving to: ‘resultados_e_metas_ufs.xlsx’

resultados_e_metas_ 100%[===================>]  15.76K  --.-KB/s    in 0.002s

2024-06-03 17:39:28 (7.28 MB/s) - ‘resultados_e_metas_ufs.xlsx’ saved [16139/16139]

In [ ]:
df_br_ufs = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_ufs.xlsx",
    skiprows=1,
)

In [ ]:
df_br_ufs.head()

,ANO,CD_UF,SIGLA_UF,NOME_UF,REDE,SAEB_2019,SAEB_2021,PC_ALUNO_ALFABETIZADO,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,PC_AVALIADOS_LP
0,2023,NaN,NaN,Brasil,PÚBLICA,54.70,35.77,55.89811,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,> 80,86
1,2023,12.0,AC,Acre,PÚBLICA,52.87,20.05,-,-,-,-,-,-,-,-,-
2,2023,27.0,AL,Alagoas,PÚBLICA,39.01,30.04,43.88,49.7,55.5,61.1,66.5,71.5,76,> 80,92.36
3,2023,13.0,AM,Amazonas,PÚBLICA,43.83,28.76,52.2,56.8,61.3,65.6,69.6,73.4,76.9,> 80,76.14
4,2023,16.0,AP,Amapá,PÚBLICA,24.77,18.77,41.56,47.6,53.8,59.9,65.6,70.9,75.8,> 80,89.68

In [ ]:
df_br_ufs.columns

Index(['ANO', 'CD_UF', 'SIGLA_UF', 'NOME_UF', 'REDE', 'SAEB_2019', 'SAEB_2021',
       'PC_ALUNO_ALFABETIZADO', 'META_FINAL_2024', 'META_FINAL_2025',
       'META_FINAL_2026', 'META_FINAL_2027', 'META_FINAL_2028',
       'META_FINAL_2029', 'META_FINAL_2030', 'PC_AVALIADOS_LP'],
      dtype='object')

In [ ]:
renames_br_ufs = {
    "ANO": "ano",
    "SIGLA_UF": "sigla_uf",
    # "NOME_UF": "nome_uf",
    "REDE": "rede",
    # "SAEB_2019": "percentual_alunos_alfabetizado_2019",
    # "SAEB_2021": "percentual_alunos_alfabetizado_2021",
    "PC_ALUNO_ALFABETIZADO": "taxa_alfabetizacao",
    "META_FINAL_2024": "meta_alfabetizacao_2024",
    "META_FINAL_2025": "meta_alfabetizacao_2025",
    "META_FINAL_2026": "meta_alfabetizacao_2026",
    "META_FINAL_2027": "meta_alfabetizacao_2027",
    "META_FINAL_2028": "meta_alfabetizacao_2028",
    "META_FINAL_2029": "meta_alfabetizacao_2029",
    "META_FINAL_2030": "meta_alfabetizacao_2030",
    "PC_AVALIADOS_LP": "percentual_participacao",
}

In [ ]:
df_br_ufs = df_br_ufs[list(renames_br_ufs.keys())].rename(
    columns=renames_br_ufs
)

In [ ]:
df_br_ufs["sigla_uf"].unique()

array([nan, 'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
       'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO',
       'RR', 'RS', 'SC', 'SE', 'SP', 'TO'], dtype=object)

In [ ]:
df_br_ufs["sigla_uf"] = df_br_ufs["sigla_uf"].replace({np.nan: "Brasil"})

In [ ]:
df_br_ufs["rede"] = df_br_ufs["rede"].replace({"PÚBLICA": "publica"})

In [ ]:
colunas_meta = [
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
    "taxa_alfabetizacao",
]
for c in colunas_meta:
    df_br_ufs[c] = (
        df_br_ufs[c]
        .astype(str)  # garante que tudo seja string para aplicar strip
        .str.strip()  # remove espaços
        .replace("-", np.nan)  # substitui "-"
        .replace("> 80", "80")
        .replace(">80", "80")  # padroniza "> 80"
        .replace(",", ".", regex=True)  # se os números forem com vírgula
    )
    df_br_ufs[c] = df_br_ufs[c].astype(float)

In [ ]:
df_br_ufs

,ano,sigla_uf,rede,percentual_alunos_alfabetizado_2021,percentual_alunos_alfabetizado_2023,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2023,Brasil,publica,35.77,55.89811,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,86.00
1,2023,AC,publica,20.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,AL,publica,30.04,43.88000,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,92.36
3,2023,AM,publica,28.76,52.20000,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,76.14
4,2023,AP,publica,18.77,41.56000,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,89.68
5,2023,BA,publica,24.49,36.80000,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,84.53
6,2023,CE,publica,44.93,84.50000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,95.22
7,2023,DF,publica,39.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023,ES,publica,46.10,67.93000,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,88.40
9,2023,GO,publica,38.94,66.70000,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,87.03
10,2023,MA,publica,22.82,56.43000,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,89.11
11,2023,MG,publica,43.17,59.81000,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,89.59
12,2023,MS,publica,30.57,47.45000,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,87.95
13,2023,MT,publica,22.31,55.06000,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,87.47
14,2023,PA,publica,36.69,48.40000,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,80.55
15,2023,PB,publica,39.16,51.12000,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,88.22
16,2023,PE,publica,27.59,59.00000,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,91.93
17,2023,PI,publica,37.33,52.48000,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,93.37
18,2023,PR,publica,39.53,73.12000,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,86.18
19,2023,RJ,publica,27.35,52.13000,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,81.21
20,2023,RN,publica,17.89,37.24000,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,78.55
21,2023,RO,publica,25.22,64.60000,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,88.10
22,2023,RR,publica,27.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2023,RS,publica,34.73,63.40000,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,81.44
24,2023,SC,publica,55.21,61.38000,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,78.60
25,2023,SE,publica,19.63,31.30000,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,88.34
26,2023,SP,publica,40.62,51.91000,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,88.75
27,2023,TO,publica,13.77,43.72000,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,83.91

In [ ]:
# df_br_ufs_long = pd.melt(
#     df_br_ufs,
#     id_vars=["sigla_uf",'meta_alfabetizacao_2024',
#        'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
#        'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
#        'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',],
#     value_vars=[
#         # "percentual_alunos_alfabetizado_2019",
#         "percentual_alunos_alfabetizado_2021",
#         "percentual_alunos_alfabetizado_2023"
#     ],
# )

In [ ]:
# df_br_ufs_long

,sigla_uf,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,variable,value
0,Brasil,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,percentual_alunos_alfabetizado_2021,35.77000
1,AC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2021,20.05000
2,AL,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,percentual_alunos_alfabetizado_2021,30.04000
3,AM,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,percentual_alunos_alfabetizado_2021,28.76000
4,AP,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,percentual_alunos_alfabetizado_2021,18.77000
5,BA,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,percentual_alunos_alfabetizado_2021,24.49000
6,CE,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,percentual_alunos_alfabetizado_2021,44.93000
7,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2021,39.85000
8,ES,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,percentual_alunos_alfabetizado_2021,46.10000
9,GO,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,percentual_alunos_alfabetizado_2021,38.94000
10,MA,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,percentual_alunos_alfabetizado_2021,22.82000
11,MG,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,percentual_alunos_alfabetizado_2021,43.17000
12,MS,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,percentual_alunos_alfabetizado_2021,30.57000
13,MT,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,percentual_alunos_alfabetizado_2021,22.31000
14,PA,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,percentual_alunos_alfabetizado_2021,36.69000
15,PB,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,percentual_alunos_alfabetizado_2021,39.16000
16,PE,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,percentual_alunos_alfabetizado_2021,27.59000
17,PI,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,percentual_alunos_alfabetizado_2021,37.33000
18,PR,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,percentual_alunos_alfabetizado_2021,39.53000
19,RJ,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,percentual_alunos_alfabetizado_2021,27.35000
20,RN,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,percentual_alunos_alfabetizado_2021,17.89000
21,RO,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,percentual_alunos_alfabetizado_2021,25.22000
22,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2021,27.31000
23,RS,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,percentual_alunos_alfabetizado_2021,34.73000
24,SC,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,percentual_alunos_alfabetizado_2021,55.21000
25,SE,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,percentual_alunos_alfabetizado_2021,19.63000
26,SP,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,percentual_alunos_alfabetizado_2021,40.62000
27,TO,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,percentual_alunos_alfabetizado_2021,13.77000
28,Brasil,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,percentual_alunos_alfabetizado_2023,55.89811
29,AC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2023,NaN
30,AL,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,percentual_alunos_alfabetizado_2023,43.88000
31,AM,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,percentual_alunos_alfabetizado_2023,52.20000
32,AP,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,percentual_alunos_alfabetizado_2023,41.56000
33,BA,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,percentual_alunos_alfabetizado_2023,36.80000
34,CE,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,percentual_alunos_alfabetizado_2023,84.50000
35,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2023,NaN
36,ES,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,percentual_alunos_alfabetizado_2023,67.93000
37,GO,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,percentual_alunos_alfabetizado_2023,66.70000
38,MA,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,percentual_alunos_alfabetizado_2023,56.43000
39,MG,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,percentual_alunos_alfabetizado_2023,59.81000
40,MS,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,percentual_alunos_alfabetizado_2023,47.45000
41,MT,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,percentual_alunos_alfabetizado_2023,55.06000
42,PA,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,percentual_alunos_alfabetizado_2023,48.40000
43,PB,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,percentual_alunos_alfabetizado_2023,51.12000
44,PE,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,percentual_alunos_alfabetizado_2023,59.00000
45,PI,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,percentual_alunos_alfabetizado_2023,52.48000
46,PR,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,percentual_alunos_alfabetizado_2023,73.12000
47,RJ,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,percentual_alunos_alfabetizado_2023,52.13000
48,RN,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,percentual_alunos_alfabetizado_2023,37.24000
49,RO,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,percentual_alunos_alfabetizado_2023,64.60000
50,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,percentual_alunos_alfabetizado_2023,NaN
51,RS,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,percentual_alunos_alfabetizado_2023,63.40000
52,SC,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,percentual_alunos_alfabetizado_2023,61.38000
53,SE,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,percentual_alunos_alfabetizado_2023,31.30000
54,SP,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,percentual_alunos_alfabetizado_2023,51.91000
55,TO,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,percentual_alunos_alfabetizado_2023,43.72000

In [ ]:
# df_br_ufs_long["variable"].unique()

array(['percentual_alunos_alfabetizado_2021',
       'percentual_alunos_alfabetizado_2023'], dtype=object)

In [ ]:
# df_br_ufs_long["variable"] = df_br_ufs_long["variable"].replace({
#     # "percentual_alunos_alfabetizado_2019": 2019,
#     "percentual_alunos_alfabetizado_2021": 2021,
#     "percentual_alunos_alfabetizado_2023": 2023
# })

/tmp/ipython-input-82-1520750076.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_br_ufs_long["variable"] = df_br_ufs_long["variable"].replace({

In [ ]:
# df_br_ufs_long = df_br_ufs_long.rename(
#     columns={"variable": "ano", "value": "taxa_alfabetizacao"}
# )

In [ ]:
# df_br_ufs_long

,sigla_uf,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,ano,taxa_alfabetizacao
0,Brasil,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,2021,35.77000
1,AC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,20.05000
2,AL,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,2021,30.04000
3,AM,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,2021,28.76000
4,AP,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,2021,18.77000
5,BA,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,2021,24.49000
6,CE,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,2021,44.93000
7,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,39.85000
8,ES,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,2021,46.10000
9,GO,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,2021,38.94000
10,MA,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,2021,22.82000
11,MG,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,2021,43.17000
12,MS,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,2021,30.57000
13,MT,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,2021,22.31000
14,PA,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,2021,36.69000
15,PB,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,2021,39.16000
16,PE,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,2021,27.59000
17,PI,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,2021,37.33000
18,PR,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,2021,39.53000
19,RJ,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,2021,27.35000
20,RN,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,2021,17.89000
21,RO,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,2021,25.22000
22,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,27.31000
23,RS,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,2021,34.73000
24,SC,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,2021,55.21000
25,SE,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,2021,19.63000
26,SP,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,2021,40.62000
27,TO,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,2021,13.77000
28,Brasil,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,2023,55.89811
29,AC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN
30,AL,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,2023,43.88000
31,AM,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,2023,52.20000
32,AP,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,2023,41.56000
33,BA,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,2023,36.80000
34,CE,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,2023,84.50000
35,DF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN
36,ES,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,2023,67.93000
37,GO,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,2023,66.70000
38,MA,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,2023,56.43000
39,MG,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,2023,59.81000
40,MS,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,2023,47.45000
41,MT,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,2023,55.06000
42,PA,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,2023,48.40000
43,PB,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,2023,51.12000
44,PE,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,2023,59.00000
45,PI,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,2023,52.48000
46,PR,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,2023,73.12000
47,RJ,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,2023,52.13000
48,RN,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,2023,37.24000
49,RO,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,2023,64.60000
50,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN
51,RS,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,2023,63.40000
52,SC,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,2023,61.38000
53,SE,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,2023,31.30000
54,SP,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,2023,51.91000
55,TO,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,2023,43.72000

In [ ]:
# df_br_ufs_long["taxa_alfabetizacao"].unique()
df_br_ufs["taxa_alfabetizacao"].unique()

array([55.89811008,         nan, 43.88      , 52.2       , 41.56      ,
       36.8       , 84.5       , 67.93      , 66.7       , 56.43      ,
       59.81      , 47.45      , 55.06      , 48.4       , 51.12      ,
       59.        , 52.48      , 73.12      , 52.13      , 37.24      ,
       64.6       , 63.4       , 61.38      , 31.3       , 51.91      ,
       43.72      ])

In [ ]:
# df_br_ufs_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sigla_uf            84 non-null     object
 1   ano                 84 non-null     int64
 2   taxa_alfabetizacao  81 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 2.1+ KB

In [ ]:
# df_br_ufs_long["taxa_alfabetizacao"] = df_br_ufs_long[
#     "taxa_alfabetizacao"
# ].replace({"- ": np.nan})

In [ ]:
df_br_ufs

,ano,sigla_uf,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao
0,2023,Brasil,publica,55.89811,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,80.0,86.00
1,2023,AC,publica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,AL,publica,43.88000,49.700000,55.500000,61.100000,66.500000,71.500000,76.000000,80.0,92.36
3,2023,AM,publica,52.20000,56.800000,61.300000,65.600000,69.600000,73.400000,76.900000,80.0,76.14
4,2023,AP,publica,41.56000,47.600000,53.800000,59.900000,65.600000,70.900000,75.800000,80.0,89.68
5,2023,BA,publica,36.80000,43.400000,50.200000,57.100000,63.600000,69.800000,75.200000,80.0,84.53
6,2023,CE,publica,84.50000,80.000000,80.000000,80.000000,80.000000,80.000000,80.000000,80.0,95.22
7,2023,DF,publica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023,ES,publica,67.93000,69.900000,71.800000,73.600000,75.300000,76.900000,78.500000,80.0,88.40
9,2023,GO,publica,66.70000,68.900000,71.000000,73.000000,74.900000,76.700000,78.400000,80.0,87.03
10,2023,MA,publica,56.43000,60.300000,64.100000,67.700000,71.200000,74.300000,77.300000,80.0,89.11
11,2023,MG,publica,59.81000,63.200000,66.400000,69.500000,72.400000,75.100000,77.600000,80.0,89.59
12,2023,MS,publica,47.45000,52.800000,58.000000,63.100000,67.900000,72.300000,76.400000,80.0,87.95
13,2023,MT,publica,55.06000,59.200000,63.200000,67.000000,70.700000,74.000000,77.200000,80.0,87.47
14,2023,PA,publica,48.40000,53.600000,58.700000,63.600000,68.200000,72.500000,76.500000,80.0,80.55
15,2023,PB,publica,51.12000,55.900000,60.500000,65.000000,69.200000,73.200000,76.800000,80.0,88.22
16,2023,PE,publica,59.00000,62.400000,65.800000,69.000000,72.100000,74.900000,77.600000,80.0,91.93
17,2023,PI,publica,52.48000,57.000000,61.500000,65.700000,69.700000,73.500000,76.900000,80.0,93.37
18,2023,PR,publica,73.12000,74.200000,75.200000,76.200000,77.200000,78.200000,79.100000,80.0,86.18
19,2023,RJ,publica,52.13000,56.700000,61.200000,65.500000,69.600000,73.400000,76.900000,80.0,81.21
20,2023,RN,publica,37.24000,43.800000,50.600000,57.300000,63.800000,69.900000,75.300000,80.0,78.55
21,2023,RO,publica,64.60000,67.100000,69.500000,71.900000,74.100000,76.200000,78.100000,80.0,88.10
22,2023,RR,publica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2023,RS,publica,63.40000,66.200000,68.800000,71.300000,73.700000,75.900000,78.000000,80.0,81.44
24,2023,SC,publica,61.38000,64.500000,67.400000,70.200000,72.900000,75.400000,77.800000,80.0,78.60
25,2023,SE,publica,31.30000,38.300000,45.900000,53.600000,61.200000,68.300000,74.600000,80.0,88.34
26,2023,SP,publica,51.91000,56.600000,61.100000,65.400000,69.500000,73.300000,76.800000,80.0,88.75
27,2023,TO,publica,43.72000,49.500000,55.400000,61.100000,66.500000,71.500000,76.000000,80.0,83.91

In [ ]:
# df_br_ufs.to_csv(
#     "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/output/br_inep_avaliacao_alfabetizacao_uf.csv",
#     index=False,
# )

# O nome dessa tabela era avaliacao_alfabetizacao_saeb_alfabetizacao_estados,
# mas esse nome não está bom. Criei um novo conjunto chamado "br_inep_avaliacao_alfabetizacao" e adicionei essa como tabela uf e a de município como municipio.

# 2024

In [ ]:
df_2023 = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_ufs.xlsx",
    sheet_name="Divulgação Alfabet UF e Brasil",
    skiprows=1,
)

In [ ]:
df_2023

,ANO,CD_UF,SIGLA_UF,NOME_UF,REDE,SAEB_2019,SAEB_2021,PC_ALUNO_ALFABETIZADO,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,PC_AVALIADOS_LP
0,2023,NaN,NaN,Brasil,PÚBLICA,54.70,35.77,55.89811,59.897807,63.769871,67.471106,70.966377,74.229525,77.243526,> 80,86
1,2023,12.0,AC,Acre,PÚBLICA,52.87,20.05,-,-,-,-,-,-,-,-,-
2,2023,27.0,AL,Alagoas,PÚBLICA,39.01,30.04,43.88,49.7,55.5,61.1,66.5,71.5,76,> 80,92.36
3,2023,13.0,AM,Amazonas,PÚBLICA,43.83,28.76,52.2,56.8,61.3,65.6,69.6,73.4,76.9,> 80,76.14
4,2023,16.0,AP,Amapá,PÚBLICA,24.77,18.77,41.56,47.6,53.8,59.9,65.6,70.9,75.8,> 80,89.68
5,2023,29.0,BA,Bahia,PÚBLICA,41.36,24.49,36.8,43.4,50.2,57.1,63.6,69.8,75.2,> 80,84.53
6,2023,23.0,CE,Ceará,PÚBLICA,73.48,44.93,84.5,>80,>80,>80,>80,>80,>80,>80,95.22
7,2023,53.0,DF,Distrito Federal,PÚBLICA,63.36,39.85,-,-,-,-,-,-,-,-,-
8,2023,32.0,ES,Espírito Santo,PÚBLICA,62.45,46.10,67.93,69.9,71.8,73.6,75.3,76.9,78.5,> 80,88.4
9,2023,52.0,GO,Goiás,PÚBLICA,63.00,38.94,66.7,68.9,71,73,74.9,76.7,78.4,> 80,87.03
10,2023,21.0,MA,Maranhão,PÚBLICA,33.14,22.82,56.43,60.3,64.1,67.7,71.2,74.3,77.3,> 80,89.11
11,2023,31.0,MG,Minas Gerais,PÚBLICA,63.70,43.17,59.81,63.2,66.4,69.5,72.4,75.1,77.6,> 80,89.59
12,2023,50.0,MS,Mato Grosso do Sul,PÚBLICA,40.68,30.57,47.45,52.8,58,63.1,67.9,72.3,76.4,> 80,87.95
13,2023,51.0,MT,Mato Grosso,PÚBLICA,52.32,22.31,55.06,59.2,63.2,67,70.7,74,77.2,> 80,87.47
14,2023,15.0,PA,Pará,PÚBLICA,37.02,36.69,48.4,53.6,58.7,63.6,68.2,72.5,76.5,> 80,80.55
15,2023,25.0,PB,Paraíba,PÚBLICA,44.98,39.16,51.12,55.9,60.5,65,69.2,73.2,76.8,> 80,88.22
16,2023,26.0,PE,Pernambuco,PÚBLICA,45.04,27.59,59,62.4,65.8,69,72.1,74.9,77.6,> 80,91.93
17,2023,22.0,PI,Piauí,PÚBLICA,49.53,37.33,52.48,57,61.5,65.7,69.7,73.5,76.9,> 80,93.37
18,2023,41.0,PR,Paraná,PÚBLICA,67.94,39.53,73.12,74.2,75.2,76.2,77.2,78.2,79.1,> 80,86.18
19,2023,33.0,RJ,Rio de Janeiro,PÚBLICA,49.44,27.35,52.13,56.7,61.2,65.5,69.6,73.4,76.9,> 80,81.21
20,2023,24.0,RN,Rio Grande do Norte,PÚBLICA,32.30,17.89,37.24,43.8,50.6,57.3,63.8,69.9,75.3,> 80,78.55
21,2023,11.0,RO,Rondônia,PÚBLICA,46.18,25.22,64.6,67.1,69.5,71.9,74.1,76.2,78.1,> 80,88.1
22,2023,14.0,RR,Roraima,PÚBLICA,45.47,27.31,-,-,-,-,-,-,-,-,-
23,2023,43.0,RS,Rio Grande do Sul,PÚBLICA,67.78,34.73,63.4,66.2,68.8,71.3,73.7,75.9,78,> 80,81.44
24,2023,42.0,SC,Santa Catarina,PÚBLICA,68.93,55.21,61.38,64.5,67.4,70.2,72.9,75.4,77.8,> 80,78.6
25,2023,28.0,SE,Sergipe,PÚBLICA,30.91,19.63,31.3,38.3,45.9,53.6,61.2,68.3,74.6,> 80,88.34
26,2023,35.0,SP,São Paulo,PÚBLICA,59.81,40.62,51.91,56.6,61.1,65.4,69.5,73.3,76.8,> 80,88.75
27,2023,17.0,TO,Tocantins,PÚBLICA,38.35,13.77,43.72,49.5,55.4,61.1,66.5,71.5,76,> 80,83.91

In [ ]:
df_2023 = df_2023.rename(
    columns={"SIGLA_UF": "SIGLA_UF", "PC_AVALIADOS_LP": "PC_AVALIADOS_LP_2023"}
)

In [ ]:
df_2024 = pd.read_excel(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/DADOS/resultados_e_metas_ufs_2024.xlsx",
    sheet_name="Divulgação Alfabet UF e Brasil",
    skiprows=1,
)

In [ ]:
df_2024.columns

Index(['ANO', 'CD_UF', 'SIGLA_UF', 'NOME_UF', 'REDE', 'SAEB_2019', 'SAEB_2021',
       'PC_ALUNO_ALFABETIZADO_2023', 'PC_ALUNO_ALFABETIZADO_2024',
       'META_FINAL_2024', 'META_FINAL_2025', 'META_FINAL_2026',
       'META_FINAL_2027', 'META_FINAL_2028', 'META_FINAL_2029',
       'META_FINAL_2030', 'PC_AVALIADOS_LP'],
      dtype='object')

In [ ]:
df_2024["SIGLA_UF"] = df_2024["SIGLA_UF"].replace({np.nan: "Brasil"})
df_2023["SIGLA_UF"] = df_2023["SIGLA_UF"].replace({np.nan: "Brasil"})

In [ ]:
df_2023["SIGLA_UF"] = df_2023["SIGLA_UF"].astype(str)
df_2024["SIGLA_UF"] = df_2024["SIGLA_UF"].astype(str)

In [ ]:
df_2024_original = df_2024.copy()

In [ ]:
df_2024_original

,ANO,CD_UF,SIGLA_UF,NOME_UF,REDE,SAEB_2019,SAEB_2021,PC_ALUNO_ALFABETIZADO_2023,PC_ALUNO_ALFABETIZADO_2024,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,PC_AVALIADOS_LP
0,2024,NaN,Brasil,Brasil,PÚBLICA,54.70,35.77,55.9,59.197271,59.9,63.77,67.47,70.97,74.23,77.24,> 80,87.37
1,2024,12.0,AC,Acre,PÚBLICA,52.87,20.05,-,51.38,-,56.9,62.2,67.3,72,76.2,> 80,80.869222
2,2024,27.0,AL,Alagoas,PÚBLICA,39.01,30.04,43.88,48.63,49.7,55.5,61.1,66.5,71.5,76,> 80,93.783968
3,2024,13.0,AM,Amazonas,PÚBLICA,43.83,28.76,52.2,49.17,56.8,61.3,65.6,69.6,73.4,76.9,> 80,79.494774
4,2024,16.0,AP,Amapá,PÚBLICA,24.77,18.77,41.56,46.62,47.6,53.8,59.9,65.6,70.9,75.8,> 80,89.141494
5,2024,29.0,BA,Bahia,PÚBLICA,41.36,24.49,36.8,35.96,43.4,50.2,57.1,63.6,69.8,75.2,> 80,90.044211
6,2024,23.0,CE,Ceará,PÚBLICA,73.48,44.93,84.5,85.31,>80,>80,>80,>80,>80,>80,>80,98.126774
7,2024,53.0,DF,Distrito Federal,PÚBLICA,63.36,39.85,-,59.13,-,63.1,67,70.6,74,77.1,>80,79.83
8,2024,32.0,ES,Espírito Santo,PÚBLICA,62.45,46.10,67.93,71.69,69.9,71.8,73.6,75.3,76.9,78.5,> 80,89.936512
9,2024,52.0,GO,Goiás,PÚBLICA,63.00,38.94,66.7,72.74,68.9,71,73,74.9,76.7,78.4,> 80,92.078733
10,2024,21.0,MA,Maranhão,PÚBLICA,33.14,22.82,56.43,59.64,60.3,64.1,67.7,71.2,74.3,77.3,> 80,90.892953
11,2024,31.0,MG,Minas Gerais,PÚBLICA,63.70,43.17,59.81,72.07,63.2,66.4,69.5,72.4,75.1,77.6,> 80,88.853063
12,2024,50.0,MS,Mato Grosso do Sul,PÚBLICA,40.68,30.57,47.45,55.87,52.8,58,63.1,67.9,72.3,76.4,> 80,90.043311
13,2024,51.0,MT,Mato Grosso,PÚBLICA,52.32,22.31,55.06,60.59,59.2,63.2,67,70.7,74,77.2,> 80,88.458746
14,2024,15.0,PA,Pará,PÚBLICA,37.02,36.69,48.4,48.2,53.6,58.7,63.6,68.2,72.5,76.5,> 80,83.21281
15,2024,25.0,PB,Paraíba,PÚBLICA,44.98,39.16,51.12,55.96,55.9,60.5,65,69.2,73.2,76.8,> 80,88.285543
16,2024,26.0,PE,Pernambuco,PÚBLICA,45.04,27.59,59,60.79,62.4,65.8,69,72.1,74.9,77.6,> 80,94.754853
17,2024,22.0,PI,Piauí,PÚBLICA,49.53,37.33,52.48,59.82,57,61.5,65.7,69.7,73.5,76.9,> 80,95.090865
18,2024,41.0,PR,Paraná,PÚBLICA,67.94,39.53,73.12,70.42,74.2,75.2,76.2,77.2,78.2,79.1,> 80,86.245321
19,2024,33.0,RJ,Rio de Janeiro,PÚBLICA,49.44,27.35,52.13,55.25,56.7,61.2,65.5,69.6,73.4,76.9,> 80,83.116196
20,2024,24.0,RN,Rio Grande do Norte,PÚBLICA,32.30,17.89,37.24,39.29,43.8,50.6,57.3,63.8,69.9,75.3,> 80,77.716929
21,2024,11.0,RO,Rondônia,PÚBLICA,46.18,25.22,64.6,62.62,67.1,69.5,71.9,74.1,76.2,78.1,> 80,88.331275
22,2024,14.0,RR,Roraima,PÚBLICA,45.47,27.31,-,-,-,-,-,-,-,-,-,-
23,2024,43.0,RS,Rio Grande do Sul,PÚBLICA,67.78,34.73,63.4,44.67,66.2,68.8,71.3,73.7,75.9,78,> 80,82.861022
24,2024,42.0,SC,Santa Catarina,PÚBLICA,68.93,55.21,61.38,62.02,64.5,67.4,70.2,72.9,75.4,77.8,> 80,70.05104
25,2024,28.0,SE,Sergipe,PÚBLICA,30.91,19.63,31.3,38.39,38.3,45.9,53.6,61.2,68.3,74.6,> 80,92.839125
26,2024,35.0,SP,São Paulo,PÚBLICA,59.81,40.62,51.91,58.13,56.6,61.1,65.4,69.5,73.3,76.8,> 80,89.117475
27,2024,17.0,TO,Tocantins,PÚBLICA,38.35,13.77,43.72,50.07,49.5,55.4,61.1,66.5,71.5,76,> 80,85.145258

In [ ]:
participacao_2023 = df_2023[["SIGLA_UF", "PC_AVALIADOS_LP_2023"]]

In [ ]:
df_2024 = df_2024.merge(
    participacao_2023,
    on="SIGLA_UF",
    how="left",  # usa left join para manter todos os dados de 2024
)

In [ ]:
df_2024

,ANO,CD_UF,SIGLA_UF,NOME_UF,REDE,SAEB_2019,SAEB_2021,PC_ALUNO_ALFABETIZADO_2023,PC_ALUNO_ALFABETIZADO_2024,META_FINAL_2024,META_FINAL_2025,META_FINAL_2026,META_FINAL_2027,META_FINAL_2028,META_FINAL_2029,META_FINAL_2030,PC_AVALIADOS_LP,PC_AVALIADOS_LP_2023
0,2024,NaN,Brasil,Brasil,PÚBLICA,54.70,35.77,55.9,59.197271,59.9,63.77,67.47,70.97,74.23,77.24,> 80,87.37,86
1,2024,12.0,AC,Acre,PÚBLICA,52.87,20.05,-,51.38,-,56.9,62.2,67.3,72,76.2,> 80,80.869222,-
2,2024,27.0,AL,Alagoas,PÚBLICA,39.01,30.04,43.88,48.63,49.7,55.5,61.1,66.5,71.5,76,> 80,93.783968,92.36
3,2024,13.0,AM,Amazonas,PÚBLICA,43.83,28.76,52.2,49.17,56.8,61.3,65.6,69.6,73.4,76.9,> 80,79.494774,76.14
4,2024,16.0,AP,Amapá,PÚBLICA,24.77,18.77,41.56,46.62,47.6,53.8,59.9,65.6,70.9,75.8,> 80,89.141494,89.68
5,2024,29.0,BA,Bahia,PÚBLICA,41.36,24.49,36.8,35.96,43.4,50.2,57.1,63.6,69.8,75.2,> 80,90.044211,84.53
6,2024,23.0,CE,Ceará,PÚBLICA,73.48,44.93,84.5,85.31,>80,>80,>80,>80,>80,>80,>80,98.126774,95.22
7,2024,53.0,DF,Distrito Federal,PÚBLICA,63.36,39.85,-,59.13,-,63.1,67,70.6,74,77.1,>80,79.83,-
8,2024,32.0,ES,Espírito Santo,PÚBLICA,62.45,46.10,67.93,71.69,69.9,71.8,73.6,75.3,76.9,78.5,> 80,89.936512,88.4
9,2024,52.0,GO,Goiás,PÚBLICA,63.00,38.94,66.7,72.74,68.9,71,73,74.9,76.7,78.4,> 80,92.078733,87.03
10,2024,21.0,MA,Maranhão,PÚBLICA,33.14,22.82,56.43,59.64,60.3,64.1,67.7,71.2,74.3,77.3,> 80,90.892953,89.11
11,2024,31.0,MG,Minas Gerais,PÚBLICA,63.70,43.17,59.81,72.07,63.2,66.4,69.5,72.4,75.1,77.6,> 80,88.853063,89.59
12,2024,50.0,MS,Mato Grosso do Sul,PÚBLICA,40.68,30.57,47.45,55.87,52.8,58,63.1,67.9,72.3,76.4,> 80,90.043311,87.95
13,2024,51.0,MT,Mato Grosso,PÚBLICA,52.32,22.31,55.06,60.59,59.2,63.2,67,70.7,74,77.2,> 80,88.458746,87.47
14,2024,15.0,PA,Pará,PÚBLICA,37.02,36.69,48.4,48.2,53.6,58.7,63.6,68.2,72.5,76.5,> 80,83.21281,80.55
15,2024,25.0,PB,Paraíba,PÚBLICA,44.98,39.16,51.12,55.96,55.9,60.5,65,69.2,73.2,76.8,> 80,88.285543,88.22
16,2024,26.0,PE,Pernambuco,PÚBLICA,45.04,27.59,59,60.79,62.4,65.8,69,72.1,74.9,77.6,> 80,94.754853,91.93
17,2024,22.0,PI,Piauí,PÚBLICA,49.53,37.33,52.48,59.82,57,61.5,65.7,69.7,73.5,76.9,> 80,95.090865,93.37
18,2024,41.0,PR,Paraná,PÚBLICA,67.94,39.53,73.12,70.42,74.2,75.2,76.2,77.2,78.2,79.1,> 80,86.245321,86.18
19,2024,33.0,RJ,Rio de Janeiro,PÚBLICA,49.44,27.35,52.13,55.25,56.7,61.2,65.5,69.6,73.4,76.9,> 80,83.116196,81.21
20,2024,24.0,RN,Rio Grande do Norte,PÚBLICA,32.30,17.89,37.24,39.29,43.8,50.6,57.3,63.8,69.9,75.3,> 80,77.716929,78.55
21,2024,11.0,RO,Rondônia,PÚBLICA,46.18,25.22,64.6,62.62,67.1,69.5,71.9,74.1,76.2,78.1,> 80,88.331275,88.1
22,2024,14.0,RR,Roraima,PÚBLICA,45.47,27.31,-,-,-,-,-,-,-,-,-,-,-
23,2024,43.0,RS,Rio Grande do Sul,PÚBLICA,67.78,34.73,63.4,44.67,66.2,68.8,71.3,73.7,75.9,78,> 80,82.861022,81.44
24,2024,42.0,SC,Santa Catarina,PÚBLICA,68.93,55.21,61.38,62.02,64.5,67.4,70.2,72.9,75.4,77.8,> 80,70.05104,78.6
25,2024,28.0,SE,Sergipe,PÚBLICA,30.91,19.63,31.3,38.39,38.3,45.9,53.6,61.2,68.3,74.6,> 80,92.839125,88.34
26,2024,35.0,SP,São Paulo,PÚBLICA,59.81,40.62,51.91,58.13,56.6,61.1,65.4,69.5,73.3,76.8,> 80,89.117475,88.75
27,2024,17.0,TO,Tocantins,PÚBLICA,38.35,13.77,43.72,50.07,49.5,55.4,61.1,66.5,71.5,76,> 80,85.145258,83.91

In [ ]:
renames = {
    "ANO": "ano",
    "SIGLA_UF": "sigla_uf",
    # "CO_MUNICIPIO": "id_municipio",
    "REDE": "rede",
    "PC_ALUNO_ALFABETIZADO_2024": "taxa_alfabetizacao_2024",
    "PC_ALUNO_ALFABETIZADO_2023": "taxa_alfabetizacao_2023",
    "META_FINAL_2024": "meta_alfabetizacao_2024",
    "META_FINAL_2025": "meta_alfabetizacao_2025",
    "META_FINAL_2026": "meta_alfabetizacao_2026",
    "META_FINAL_2027": "meta_alfabetizacao_2027",
    "META_FINAL_2028": "meta_alfabetizacao_2028",
    "META_FINAL_2029": "meta_alfabetizacao_2029",
    "META_FINAL_2030": "meta_alfabetizacao_2030",
    # "CO_NIVEL_ALFABETIZACAO": "nivel_alfabetizacao_2024",
    "PC_AVALIADOS_LP": "percentual_participacao_2024",
    "PC_AVALIADOS_LP_2023": "percentual_participacao_2023",
    # "NIVEIS_ALFABETIZACAO_2023": "nivel_alfabetizacao_2023"
}

In [ ]:
df_2024 = df_2024[list(renames.keys())].rename(columns=renames)

In [ ]:
df_2024

,ano,sigla_uf,rede,taxa_alfabetizacao_2024,taxa_alfabetizacao_2023,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao_2024,percentual_participacao_2023
0,2024,Brasil,PÚBLICA,59.197271,55.9,59.9,63.77,67.47,70.97,74.23,77.24,> 80,87.37,86
1,2024,AC,PÚBLICA,51.38,-,-,56.9,62.2,67.3,72,76.2,> 80,80.869222,-
2,2024,AL,PÚBLICA,48.63,43.88,49.7,55.5,61.1,66.5,71.5,76,> 80,93.783968,92.36
3,2024,AM,PÚBLICA,49.17,52.2,56.8,61.3,65.6,69.6,73.4,76.9,> 80,79.494774,76.14
4,2024,AP,PÚBLICA,46.62,41.56,47.6,53.8,59.9,65.6,70.9,75.8,> 80,89.141494,89.68
5,2024,BA,PÚBLICA,35.96,36.8,43.4,50.2,57.1,63.6,69.8,75.2,> 80,90.044211,84.53
6,2024,CE,PÚBLICA,85.31,84.5,>80,>80,>80,>80,>80,>80,>80,98.126774,95.22
7,2024,DF,PÚBLICA,59.13,-,-,63.1,67,70.6,74,77.1,>80,79.83,-
8,2024,ES,PÚBLICA,71.69,67.93,69.9,71.8,73.6,75.3,76.9,78.5,> 80,89.936512,88.4
9,2024,GO,PÚBLICA,72.74,66.7,68.9,71,73,74.9,76.7,78.4,> 80,92.078733,87.03
10,2024,MA,PÚBLICA,59.64,56.43,60.3,64.1,67.7,71.2,74.3,77.3,> 80,90.892953,89.11
11,2024,MG,PÚBLICA,72.07,59.81,63.2,66.4,69.5,72.4,75.1,77.6,> 80,88.853063,89.59
12,2024,MS,PÚBLICA,55.87,47.45,52.8,58,63.1,67.9,72.3,76.4,> 80,90.043311,87.95
13,2024,MT,PÚBLICA,60.59,55.06,59.2,63.2,67,70.7,74,77.2,> 80,88.458746,87.47
14,2024,PA,PÚBLICA,48.2,48.4,53.6,58.7,63.6,68.2,72.5,76.5,> 80,83.21281,80.55
15,2024,PB,PÚBLICA,55.96,51.12,55.9,60.5,65,69.2,73.2,76.8,> 80,88.285543,88.22
16,2024,PE,PÚBLICA,60.79,59,62.4,65.8,69,72.1,74.9,77.6,> 80,94.754853,91.93
17,2024,PI,PÚBLICA,59.82,52.48,57,61.5,65.7,69.7,73.5,76.9,> 80,95.090865,93.37
18,2024,PR,PÚBLICA,70.42,73.12,74.2,75.2,76.2,77.2,78.2,79.1,> 80,86.245321,86.18
19,2024,RJ,PÚBLICA,55.25,52.13,56.7,61.2,65.5,69.6,73.4,76.9,> 80,83.116196,81.21
20,2024,RN,PÚBLICA,39.29,37.24,43.8,50.6,57.3,63.8,69.9,75.3,> 80,77.716929,78.55
21,2024,RO,PÚBLICA,62.62,64.6,67.1,69.5,71.9,74.1,76.2,78.1,> 80,88.331275,88.1
22,2024,RR,PÚBLICA,-,-,-,-,-,-,-,-,-,-,-
23,2024,RS,PÚBLICA,44.67,63.4,66.2,68.8,71.3,73.7,75.9,78,> 80,82.861022,81.44
24,2024,SC,PÚBLICA,62.02,61.38,64.5,67.4,70.2,72.9,75.4,77.8,> 80,70.05104,78.6
25,2024,SE,PÚBLICA,38.39,31.3,38.3,45.9,53.6,61.2,68.3,74.6,> 80,92.839125,88.34
26,2024,SP,PÚBLICA,58.13,51.91,56.6,61.1,65.4,69.5,73.3,76.8,> 80,89.117475,88.75
27,2024,TO,PÚBLICA,50.07,43.72,49.5,55.4,61.1,66.5,71.5,76,> 80,85.145258,83.91

In [ ]:
df_2024.columns

Index(['ano', 'sigla_uf', 'rede', 'taxa_alfabetizacao_2024',
       'taxa_alfabetizacao_2023', 'meta_alfabetizacao_2024',
       'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
       'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
       'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',
       'percentual_participacao_2024', 'percentual_participacao_2023'],
      dtype='object')

In [ ]:
colunas_meta = [
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
    "taxa_alfabetizacao_2023",
    "taxa_alfabetizacao_2024",
    "percentual_participacao_2023",
    "percentual_participacao_2024",
]
for c in colunas_meta:
    df_2024[c] = (
        df_2024[c]
        .astype(str)  # garante que tudo seja string para aplicar strip
        .str.strip()  # remove espaços
        .replace("-", np.nan)  # substitui "-"
        .replace("> 80", "80")
        .replace(">80", "80")  # padroniza "> 80"
        .replace(",", ".", regex=True)  # se os números forem com vírgula
    )
    df_2024[c] = df_2024[c].astype(float)

In [ ]:
df_2024

,ano,sigla_uf,rede,taxa_alfabetizacao_2024,taxa_alfabetizacao_2023,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao_2024,percentual_participacao_2023
0,2024,Brasil,PÚBLICA,59.197271,55.90,59.9,63.77,67.47,70.97,74.23,77.24,80.0,87.370000,86.00
1,2024,AC,PÚBLICA,51.380000,NaN,NaN,56.90,62.20,67.30,72.00,76.20,80.0,80.869222,NaN
2,2024,AL,PÚBLICA,48.630000,43.88,49.7,55.50,61.10,66.50,71.50,76.00,80.0,93.783968,92.36
3,2024,AM,PÚBLICA,49.170000,52.20,56.8,61.30,65.60,69.60,73.40,76.90,80.0,79.494774,76.14
4,2024,AP,PÚBLICA,46.620000,41.56,47.6,53.80,59.90,65.60,70.90,75.80,80.0,89.141494,89.68
5,2024,BA,PÚBLICA,35.960000,36.80,43.4,50.20,57.10,63.60,69.80,75.20,80.0,90.044211,84.53
6,2024,CE,PÚBLICA,85.310000,84.50,80.0,80.00,80.00,80.00,80.00,80.00,80.0,98.126774,95.22
7,2024,DF,PÚBLICA,59.130000,NaN,NaN,63.10,67.00,70.60,74.00,77.10,80.0,79.830000,NaN
8,2024,ES,PÚBLICA,71.690000,67.93,69.9,71.80,73.60,75.30,76.90,78.50,80.0,89.936512,88.40
9,2024,GO,PÚBLICA,72.740000,66.70,68.9,71.00,73.00,74.90,76.70,78.40,80.0,92.078733,87.03
10,2024,MA,PÚBLICA,59.640000,56.43,60.3,64.10,67.70,71.20,74.30,77.30,80.0,90.892953,89.11
11,2024,MG,PÚBLICA,72.070000,59.81,63.2,66.40,69.50,72.40,75.10,77.60,80.0,88.853063,89.59
12,2024,MS,PÚBLICA,55.870000,47.45,52.8,58.00,63.10,67.90,72.30,76.40,80.0,90.043311,87.95
13,2024,MT,PÚBLICA,60.590000,55.06,59.2,63.20,67.00,70.70,74.00,77.20,80.0,88.458746,87.47
14,2024,PA,PÚBLICA,48.200000,48.40,53.6,58.70,63.60,68.20,72.50,76.50,80.0,83.212810,80.55
15,2024,PB,PÚBLICA,55.960000,51.12,55.9,60.50,65.00,69.20,73.20,76.80,80.0,88.285543,88.22
16,2024,PE,PÚBLICA,60.790000,59.00,62.4,65.80,69.00,72.10,74.90,77.60,80.0,94.754853,91.93
17,2024,PI,PÚBLICA,59.820000,52.48,57.0,61.50,65.70,69.70,73.50,76.90,80.0,95.090865,93.37
18,2024,PR,PÚBLICA,70.420000,73.12,74.2,75.20,76.20,77.20,78.20,79.10,80.0,86.245321,86.18
19,2024,RJ,PÚBLICA,55.250000,52.13,56.7,61.20,65.50,69.60,73.40,76.90,80.0,83.116196,81.21
20,2024,RN,PÚBLICA,39.290000,37.24,43.8,50.60,57.30,63.80,69.90,75.30,80.0,77.716929,78.55
21,2024,RO,PÚBLICA,62.620000,64.60,67.1,69.50,71.90,74.10,76.20,78.10,80.0,88.331275,88.10
22,2024,RR,PÚBLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2024,RS,PÚBLICA,44.670000,63.40,66.2,68.80,71.30,73.70,75.90,78.00,80.0,82.861022,81.44
24,2024,SC,PÚBLICA,62.020000,61.38,64.5,67.40,70.20,72.90,75.40,77.80,80.0,70.051040,78.60
25,2024,SE,PÚBLICA,38.390000,31.30,38.3,45.90,53.60,61.20,68.30,74.60,80.0,92.839125,88.34
26,2024,SP,PÚBLICA,58.130000,51.91,56.6,61.10,65.40,69.50,73.30,76.80,80.0,89.117475,88.75
27,2024,TO,PÚBLICA,50.070000,43.72,49.5,55.40,61.10,66.50,71.50,76.00,80.0,85.145258,83.91

In [ ]:
df_2024.columns

Index(['ano', 'sigla_uf', 'rede', 'taxa_alfabetizacao_2024',
       'taxa_alfabetizacao_2023', 'meta_alfabetizacao_2024',
       'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
       'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
       'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',
       'percentual_participacao_2024', 'percentual_participacao_2023'],
      dtype='object')

In [ ]:
# Lista de colunas fixas (que não vão para long)
id_vars = [
    "sigla_uf",
    "rede",
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
]


# Função auxiliar para "derreter" um grupo de colunas por variável
def melt_por_variavel(df, variavel):
    colunas = [f"{variavel}_2023", f"{variavel}_2024"]
    df_melted = df_2024[id_vars + colunas].melt(
        id_vars=id_vars,
        value_vars=colunas,
        var_name="variavel_ano",
        value_name=variavel,
    )
    # Extrai o ano da string da coluna e transforma em inteiro
    df_melted["ano"] = (
        df_melted["variavel_ano"].str.extract(r"(\d{4})").astype(int)
    )
    df_melted = df_melted.drop(columns="variavel_ano")
    return df_melted


# Faz o melt para cada variável que será empilhada
df_taxa = melt_por_variavel(df_2024, "taxa_alfabetizacao")
# df_nivel = melt_por_variavel(df_2024, 'nivel_alfabetizacao')
df_participacao = melt_por_variavel(df_2024, "percentual_participacao")

# Junta tudo pelo conjunto de chaves
df_long = df_taxa.merge(df_participacao, on=id_vars + ["ano"])

In [ ]:
df_long

,sigla_uf,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,percentual_participacao
0,Brasil,PÚBLICA,59.9,63.77,67.47,70.97,74.23,77.24,80.0,55.900000,2023,86.000000
1,AC,PÚBLICA,NaN,56.90,62.20,67.30,72.00,76.20,80.0,NaN,2023,NaN
2,AL,PÚBLICA,49.7,55.50,61.10,66.50,71.50,76.00,80.0,43.880000,2023,92.360000
3,AM,PÚBLICA,56.8,61.30,65.60,69.60,73.40,76.90,80.0,52.200000,2023,76.140000
4,AP,PÚBLICA,47.6,53.80,59.90,65.60,70.90,75.80,80.0,41.560000,2023,89.680000
5,BA,PÚBLICA,43.4,50.20,57.10,63.60,69.80,75.20,80.0,36.800000,2023,84.530000
6,CE,PÚBLICA,80.0,80.00,80.00,80.00,80.00,80.00,80.0,84.500000,2023,95.220000
7,DF,PÚBLICA,NaN,63.10,67.00,70.60,74.00,77.10,80.0,NaN,2023,NaN
8,ES,PÚBLICA,69.9,71.80,73.60,75.30,76.90,78.50,80.0,67.930000,2023,88.400000
9,GO,PÚBLICA,68.9,71.00,73.00,74.90,76.70,78.40,80.0,66.700000,2023,87.030000
10,MA,PÚBLICA,60.3,64.10,67.70,71.20,74.30,77.30,80.0,56.430000,2023,89.110000
11,MG,PÚBLICA,63.2,66.40,69.50,72.40,75.10,77.60,80.0,59.810000,2023,89.590000
12,MS,PÚBLICA,52.8,58.00,63.10,67.90,72.30,76.40,80.0,47.450000,2023,87.950000
13,MT,PÚBLICA,59.2,63.20,67.00,70.70,74.00,77.20,80.0,55.060000,2023,87.470000
14,PA,PÚBLICA,53.6,58.70,63.60,68.20,72.50,76.50,80.0,48.400000,2023,80.550000
15,PB,PÚBLICA,55.9,60.50,65.00,69.20,73.20,76.80,80.0,51.120000,2023,88.220000
16,PE,PÚBLICA,62.4,65.80,69.00,72.10,74.90,77.60,80.0,59.000000,2023,91.930000
17,PI,PÚBLICA,57.0,61.50,65.70,69.70,73.50,76.90,80.0,52.480000,2023,93.370000
18,PR,PÚBLICA,74.2,75.20,76.20,77.20,78.20,79.10,80.0,73.120000,2023,86.180000
19,RJ,PÚBLICA,56.7,61.20,65.50,69.60,73.40,76.90,80.0,52.130000,2023,81.210000
20,RN,PÚBLICA,43.8,50.60,57.30,63.80,69.90,75.30,80.0,37.240000,2023,78.550000
21,RO,PÚBLICA,67.1,69.50,71.90,74.10,76.20,78.10,80.0,64.600000,2023,88.100000
22,RR,PÚBLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN
23,RS,PÚBLICA,66.2,68.80,71.30,73.70,75.90,78.00,80.0,63.400000,2023,81.440000
24,SC,PÚBLICA,64.5,67.40,70.20,72.90,75.40,77.80,80.0,61.380000,2023,78.600000
25,SE,PÚBLICA,38.3,45.90,53.60,61.20,68.30,74.60,80.0,31.300000,2023,88.340000
26,SP,PÚBLICA,56.6,61.10,65.40,69.50,73.30,76.80,80.0,51.910000,2023,88.750000
27,TO,PÚBLICA,49.5,55.40,61.10,66.50,71.50,76.00,80.0,43.720000,2023,83.910000
28,Brasil,PÚBLICA,59.9,63.77,67.47,70.97,74.23,77.24,80.0,59.197271,2024,87.370000
29,AC,PÚBLICA,NaN,56.90,62.20,67.30,72.00,76.20,80.0,51.380000,2024,80.869222
30,AL,PÚBLICA,49.7,55.50,61.10,66.50,71.50,76.00,80.0,48.630000,2024,93.783968
31,AM,PÚBLICA,56.8,61.30,65.60,69.60,73.40,76.90,80.0,49.170000,2024,79.494774
32,AP,PÚBLICA,47.6,53.80,59.90,65.60,70.90,75.80,80.0,46.620000,2024,89.141494
33,BA,PÚBLICA,43.4,50.20,57.10,63.60,69.80,75.20,80.0,35.960000,2024,90.044211
34,CE,PÚBLICA,80.0,80.00,80.00,80.00,80.00,80.00,80.0,85.310000,2024,98.126774
35,DF,PÚBLICA,NaN,63.10,67.00,70.60,74.00,77.10,80.0,59.130000,2024,79.830000
36,ES,PÚBLICA,69.9,71.80,73.60,75.30,76.90,78.50,80.0,71.690000,2024,89.936512
37,GO,PÚBLICA,68.9,71.00,73.00,74.90,76.70,78.40,80.0,72.740000,2024,92.078733
38,MA,PÚBLICA,60.3,64.10,67.70,71.20,74.30,77.30,80.0,59.640000,2024,90.892953
39,MG,PÚBLICA,63.2,66.40,69.50,72.40,75.10,77.60,80.0,72.070000,2024,88.853063
40,MS,PÚBLICA,52.8,58.00,63.10,67.90,72.30,76.40,80.0,55.870000,2024,90.043311
41,MT,PÚBLICA,59.2,63.20,67.00,70.70,74.00,77.20,80.0,60.590000,2024,88.458746
42,PA,PÚBLICA,53.6,58.70,63.60,68.20,72.50,76.50,80.0,48.200000,2024,83.212810
43,PB,PÚBLICA,55.9,60.50,65.00,69.20,73.20,76.80,80.0,55.960000,2024,88.285543
44,PE,PÚBLICA,62.4,65.80,69.00,72.10,74.90,77.60,80.0,60.790000,2024,94.754853
45,PI,PÚBLICA,57.0,61.50,65.70,69.70,73.50,76.90,80.0,59.820000,2024,95.090865
46,PR,PÚBLICA,74.2,75.20,76.20,77.20,78.20,79.10,80.0,70.420000,2024,86.245321
47,RJ,PÚBLICA,56.7,61.20,65.50,69.60,73.40,76.90,80.0,55.250000,2024,83.116196
48,RN,PÚBLICA,43.8,50.60,57.30,63.80,69.90,75.30,80.0,39.290000,2024,77.716929
49,RO,PÚBLICA,67.1,69.50,71.90,74.10,76.20,78.10,80.0,62.620000,2024,88.331275
50,RR,PÚBLICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN
51,RS,PÚBLICA,66.2,68.80,71.30,73.70,75.90,78.00,80.0,44.670000,2024,82.861022
52,SC,PÚBLICA,64.5,67.40,70.20,72.90,75.40,77.80,80.0,62.020000,2024,70.051040
53,SE,PÚBLICA,38.3,45.90,53.60,61.20,68.30,74.60,80.0,38.390000,2024,92.839125
54,SP,PÚBLICA,56.6,61.10,65.40,69.50,73.30,76.80,80.0,58.130000,2024,89.117475
55,TO,PÚBLICA,49.5,55.40,61.10,66.50,71.50,76.00,80.0,50.070000,2024,85.145258

In [ ]:
df_long["sigla_uf"].unique()

array(['Brasil', 'AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO',
       'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN',
       'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO'], dtype=object)

In [ ]:
df_long["rede"] = df_long["rede"].replace({"PÚBLICA": "publica"})

In [ ]:
df_long

,sigla_uf,rede,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,taxa_alfabetizacao,ano,percentual_participacao
0,Brasil,publica,59.9,63.77,67.47,70.97,74.23,77.24,80.0,55.900000,2023,86.000000
1,AC,publica,NaN,56.90,62.20,67.30,72.00,76.20,80.0,NaN,2023,NaN
2,AL,publica,49.7,55.50,61.10,66.50,71.50,76.00,80.0,43.880000,2023,92.360000
3,AM,publica,56.8,61.30,65.60,69.60,73.40,76.90,80.0,52.200000,2023,76.140000
4,AP,publica,47.6,53.80,59.90,65.60,70.90,75.80,80.0,41.560000,2023,89.680000
5,BA,publica,43.4,50.20,57.10,63.60,69.80,75.20,80.0,36.800000,2023,84.530000
6,CE,publica,80.0,80.00,80.00,80.00,80.00,80.00,80.0,84.500000,2023,95.220000
7,DF,publica,NaN,63.10,67.00,70.60,74.00,77.10,80.0,NaN,2023,NaN
8,ES,publica,69.9,71.80,73.60,75.30,76.90,78.50,80.0,67.930000,2023,88.400000
9,GO,publica,68.9,71.00,73.00,74.90,76.70,78.40,80.0,66.700000,2023,87.030000
10,MA,publica,60.3,64.10,67.70,71.20,74.30,77.30,80.0,56.430000,2023,89.110000
11,MG,publica,63.2,66.40,69.50,72.40,75.10,77.60,80.0,59.810000,2023,89.590000
12,MS,publica,52.8,58.00,63.10,67.90,72.30,76.40,80.0,47.450000,2023,87.950000
13,MT,publica,59.2,63.20,67.00,70.70,74.00,77.20,80.0,55.060000,2023,87.470000
14,PA,publica,53.6,58.70,63.60,68.20,72.50,76.50,80.0,48.400000,2023,80.550000
15,PB,publica,55.9,60.50,65.00,69.20,73.20,76.80,80.0,51.120000,2023,88.220000
16,PE,publica,62.4,65.80,69.00,72.10,74.90,77.60,80.0,59.000000,2023,91.930000
17,PI,publica,57.0,61.50,65.70,69.70,73.50,76.90,80.0,52.480000,2023,93.370000
18,PR,publica,74.2,75.20,76.20,77.20,78.20,79.10,80.0,73.120000,2023,86.180000
19,RJ,publica,56.7,61.20,65.50,69.60,73.40,76.90,80.0,52.130000,2023,81.210000
20,RN,publica,43.8,50.60,57.30,63.80,69.90,75.30,80.0,37.240000,2023,78.550000
21,RO,publica,67.1,69.50,71.90,74.10,76.20,78.10,80.0,64.600000,2023,88.100000
22,RR,publica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN
23,RS,publica,66.2,68.80,71.30,73.70,75.90,78.00,80.0,63.400000,2023,81.440000
24,SC,publica,64.5,67.40,70.20,72.90,75.40,77.80,80.0,61.380000,2023,78.600000
25,SE,publica,38.3,45.90,53.60,61.20,68.30,74.60,80.0,31.300000,2023,88.340000
26,SP,publica,56.6,61.10,65.40,69.50,73.30,76.80,80.0,51.910000,2023,88.750000
27,TO,publica,49.5,55.40,61.10,66.50,71.50,76.00,80.0,43.720000,2023,83.910000
28,Brasil,publica,59.9,63.77,67.47,70.97,74.23,77.24,80.0,59.197271,2024,87.370000
29,AC,publica,NaN,56.90,62.20,67.30,72.00,76.20,80.0,51.380000,2024,80.869222
30,AL,publica,49.7,55.50,61.10,66.50,71.50,76.00,80.0,48.630000,2024,93.783968
31,AM,publica,56.8,61.30,65.60,69.60,73.40,76.90,80.0,49.170000,2024,79.494774
32,AP,publica,47.6,53.80,59.90,65.60,70.90,75.80,80.0,46.620000,2024,89.141494
33,BA,publica,43.4,50.20,57.10,63.60,69.80,75.20,80.0,35.960000,2024,90.044211
34,CE,publica,80.0,80.00,80.00,80.00,80.00,80.00,80.0,85.310000,2024,98.126774
35,DF,publica,NaN,63.10,67.00,70.60,74.00,77.10,80.0,59.130000,2024,79.830000
36,ES,publica,69.9,71.80,73.60,75.30,76.90,78.50,80.0,71.690000,2024,89.936512
37,GO,publica,68.9,71.00,73.00,74.90,76.70,78.40,80.0,72.740000,2024,92.078733
38,MA,publica,60.3,64.10,67.70,71.20,74.30,77.30,80.0,59.640000,2024,90.892953
39,MG,publica,63.2,66.40,69.50,72.40,75.10,77.60,80.0,72.070000,2024,88.853063
40,MS,publica,52.8,58.00,63.10,67.90,72.30,76.40,80.0,55.870000,2024,90.043311
41,MT,publica,59.2,63.20,67.00,70.70,74.00,77.20,80.0,60.590000,2024,88.458746
42,PA,publica,53.6,58.70,63.60,68.20,72.50,76.50,80.0,48.200000,2024,83.212810
43,PB,publica,55.9,60.50,65.00,69.20,73.20,76.80,80.0,55.960000,2024,88.285543
44,PE,publica,62.4,65.80,69.00,72.10,74.90,77.60,80.0,60.790000,2024,94.754853
45,PI,publica,57.0,61.50,65.70,69.70,73.50,76.90,80.0,59.820000,2024,95.090865
46,PR,publica,74.2,75.20,76.20,77.20,78.20,79.10,80.0,70.420000,2024,86.245321
47,RJ,publica,56.7,61.20,65.50,69.60,73.40,76.90,80.0,55.250000,2024,83.116196
48,RN,publica,43.8,50.60,57.30,63.80,69.90,75.30,80.0,39.290000,2024,77.716929
49,RO,publica,67.1,69.50,71.90,74.10,76.20,78.10,80.0,62.620000,2024,88.331275
50,RR,publica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024,NaN
51,RS,publica,66.2,68.80,71.30,73.70,75.90,78.00,80.0,44.670000,2024,82.861022
52,SC,publica,64.5,67.40,70.20,72.90,75.40,77.80,80.0,62.020000,2024,70.051040
53,SE,publica,38.3,45.90,53.60,61.20,68.30,74.60,80.0,38.390000,2024,92.839125
54,SP,publica,56.6,61.10,65.40,69.50,73.30,76.80,80.0,58.130000,2024,89.117475
55,TO,publica,49.5,55.40,61.10,66.50,71.50,76.00,80.0,50.070000,2024,85.145258

In [ ]:
df_long["taxa_alfabetizacao"].unique()

array([55.9       ,         nan, 43.88      , 52.2       , 41.56      ,
       36.8       , 84.5       , 67.93      , 66.7       , 56.43      ,
       59.81      , 47.45      , 55.06      , 48.4       , 51.12      ,
       59.        , 52.48      , 73.12      , 52.13      , 37.24      ,
       64.6       , 63.4       , 61.38      , 31.3       , 51.91      ,
       43.72      , 59.19727063, 51.38      , 48.63      , 49.17      ,
       46.62      , 35.96      , 85.31      , 59.13      , 71.69      ,
       72.74      , 59.64      , 72.07      , 55.87      , 60.59      ,
       48.2       , 55.96      , 60.79      , 59.82      , 70.42      ,
       55.25      , 39.29      , 62.62      , 44.67      , 62.02      ,
       38.39      , 58.13      , 50.07      ])

In [ ]:
df_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sigla_uf                 56 non-null     object
 1   rede                     56 non-null     object
 2   meta_alfabetizacao_2024  50 non-null     float64
 3   meta_alfabetizacao_2025  54 non-null     float64
 4   meta_alfabetizacao_2026  54 non-null     float64
 5   meta_alfabetizacao_2027  54 non-null     float64
 6   meta_alfabetizacao_2028  54 non-null     float64
 7   meta_alfabetizacao_2029  54 non-null     float64
 8   meta_alfabetizacao_2030  54 non-null     float64
 9   taxa_alfabetizacao       52 non-null     float64
 10  ano                      56 non-null     int64
 11  percentual_participacao  52 non-null     float64
dtypes: float64(9), int64(1), object(2)
memory usage: 5.4+ KB

In [ ]:
df_long.columns

Index(['sigla_uf', 'rede', 'meta_alfabetizacao_2024',
       'meta_alfabetizacao_2025', 'meta_alfabetizacao_2026',
       'meta_alfabetizacao_2027', 'meta_alfabetizacao_2028',
       'meta_alfabetizacao_2029', 'meta_alfabetizacao_2030',
       'taxa_alfabetizacao', 'ano', 'percentual_participacao'],
      dtype='object')

In [ ]:
ordem = [
    "ano",
    "sigla_uf",
    "rede",
    "taxa_alfabetizacao",
    "meta_alfabetizacao_2024",
    "meta_alfabetizacao_2025",
    "meta_alfabetizacao_2026",
    "meta_alfabetizacao_2027",
    "meta_alfabetizacao_2028",
    "meta_alfabetizacao_2029",
    "meta_alfabetizacao_2030",
    "percentual_participacao",
]

In [ ]:
# df_br_ufs_long["taxa_alfabetizacao"] = df_br_ufs_long[
#     "taxa_alfabetizacao"
# ].replace({"- ": np.nan})

In [ ]:
df_long = df_long[ordem]

In [ ]:
# df = pd.concat([df_2023, df_2024])

In [ ]:
df_long = df_long.sort_values(by=["ano", "sigla_uf"])

In [ ]:
df_long.to_csv(
    "/content/drive/MyDrive/Base dos Dados <> Fundação Lemann/Demandas/Alfabetização - Dados - Avaliações estaduais 2023/output/br_inep_avaliacao_alfabetizacao_uf.csv",
    index=False,
)

# O nome dessa tabela hoje é avaliacao_alfabetizacao_saeb_alfabetizacao_estados,
# mas esse nome não está bom. Vou atualizá-la mantendo esse nome pra acelerar a atualização do dashboard,
#  mas seria bom que com a chegada dos dados de 2024 pudéssemos
# substituí-la por esse novo nome, talvez até subi-la na BD (acho que é um dado bom de ter lá).